
#region System
public enum CURSOR_MODE
{
    LOCK,
    UNLOCK
}

public enum CALCULATE_MODE
{
    Absolute,
    Ratio
}
#endregion

#region Combat
public enum HIT_TYPE
{
    // Attack
    NORMAL = 0,
    LIGHT = 1,
    HEAVY = 2,
    STUN = 3,

    NONE = 100,
}

public enum GUARD_TYPE
{
    GUARDABLE,
    PARRYABLE,

    NONE = 100,
}

public enum COMBAT_ACTION_TYPE
{
    // Halberd
    HALBERD_ATTACK_LIGHT_01,
    HALBERD_ATTACK_LIGHT_02,
    HALBERD_ATTACK_LIGHT_03,
    HALBERD_ATTACK_LIGHT_04,

    HALBERD_ATTACK_HEAVY_01,
    HALBERD_ATTACK_HEAVY_02,
    HALBERD_ATTACK_HEAVY_03,
    HALBERD_ATTACK_HEAVY_04,

    HALBERD_GUARD_IN,
    HALBERD_GUARD_LOOP,
    HALBERD_GUARD_OUT,
    HALBERD_GUARD_BREAK,
    HALBERD_PARRYING,
    HALBERD_PARRYING_ATTACK,

    HALBERD_SKILL_COUNTER,

    // Sword & Shield
    SWORD_SHIELD_ATTACK_LIGHT_01,
    SWORD_SHIELD_ATTACK_LIGHT_02,
    SWORD_SHIELD_ATTACK_LIGHT_03,
    SWORD_SHIELD_ATTACK_LIGHT_04,

    SWORD_SHIELD_ATTACK_HEAVY_01,
    SWORD_SHIELD_ATTACK_HEAVY_02,
    SWORD_SHIELD_ATTACK_HEAVY_03,
    SWORD_SHIELD_ATTACK_HEAVY_04_01,
    SWORD_SHIELD_ATTACK_HEAVY_04_02,

    SWORD_SHIELD_GUARD_IN,
    SWORD_SHIELD_GUARD_LOOP,
    SWORD_SHIELD_GUARD_OUT,
    SWORD_SHIELD_GUARD_BREAK,
    SWORD_SHIELD_PARRYING,
    SWORD_SHIELD_PARRYING_ATTACK,
}

public enum WEAPON_TYPE
{
    None,
    HALBERD,
    SWORD_SHIELD,
}
#endregion

#region State
public enum ACTION_STATE
{
    // Common State
    COMMON_UPPER_EMPTY = 20000,

    // Player State
    // - Common
    PLAYER_DRINK = 1,
    PLAYER_ROLL = 8,

    PLAYER_RESONANCE_IN = 16,
    PLAYER_RESONANCE_LOOP = 17,
    PLAYER_RESONANCE_OUT = 18,

    PLAYER_HIT_LIGHT = 32,
    PLAYER_HIT_HEAVY = 33,
    PLAYER_HIT_HEAVY_LOOP = 34,
    PLAYER_STAND_UP = 35,
    PLAYER_STAND_ROLL = 36,

    PLAYER_SLIDE = 64,
    PLAYER_FALL = 65,
    PLAYER_LANDING = 66,

    PLAYER_STUN = 128,

    PLAYER_COMPETE = 256,
    PLAYER_COMPETE_SUCCESS = 257,
    PLAYER_SPAWN = 512,
    PLAYER_DIE = 513,

    // - Halberd
    PLAYER_HALBERD_IDLE = 1000,
    PLAYER_HALBERD_WALK = 1001,
    PLAYER_HALBERD_RUN = 1002,

    PLAYER_HALBERD_EQUIP = 1003,

    PLAYER_HALBERD_ATTACK_LIGHT_01 = 1008,
    PLAYER_HALBERD_ATTACK_LIGHT_02 = 1009,
    PLAYER_HALBERD_ATTACK_LIGHT_03 = 1010,
    PLAYER_HALBERD_ATTACK_LIGHT_04 = 1011,

    PLAYER_HALBERD_ATTACK_HEAVY_01 = 1012,
    PLAYER_HALBERD_ATTACK_HEAVY_02 = 1013,
    PLAYER_HALBERD_ATTACK_HEAVY_03 = 1014,
    PLAYER_HALBERD_ATTACK_HEAVY_04 = 1015,

    PLAYER_HALBERD_GUARD_IN = 1016,
    PLAYER_HALBERD_GUARD_LOOP = 1017,
    PLAYER_HALBERD_GUARD_OUT = 1018,
    PLAYER_HALBERD_GUARD_BREAK = 1019,
    PLAYER_HALBERD_PARRYING = 1020,
    PLAYER_HALBERD_PARRYING_ATTACK = 1021,

    PLAYER_HALBERD_SKILL_COUNTER = 1022,

    // - Sword Shield
    PLAYER_SWORD_SHIELD_IDLE = 1100,
    PLAYER_SWORD_SHIELD_WALK = 1101,
    PLAYER_SWORD_SHIELD_RUN = 1102,

    PLAYER_SWORD_SHIELD_EQUIP = 1103,

    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_01 = 1108,
    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_02 = 1109,
    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_03 = 1110,
    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_04 = 1111,

    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_01 = 1112,
    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_02 = 1113,
    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_03 = 1114,
    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_04 = 1115,

    PLAYER_SWORD_SHIELD_GUARD_IN = 1116,
    PLAYER_SWORD_SHIELD_GUARD_LOOP = 1117,
    PLAYER_SWORD_SHIELD_GUARD_OUT = 1118,
    PLAYER_SWORD_SHIELD_GUARD_BREAK = 1119,
    PLAYER_SWORD_SHIELD_PARRYING = 1120,
    PLAYER_SWORD_SHIELD_PARRYING_ATTACK = 1121,

    // Enemy State
    ENEMY_IDLE = 10000,
    ENEMY_PATROL = 10001,
    ENEMY_CHASE_WAIT = 10002,
    ENEMY_CHASE_TURN = 10003,
    ENEMY_CHASE_WALK = 10004,
    ENEMY_CHASE_RUN = 10005,

    ENEMY_SLIDE = 10258,
    ENEMY_FALL = 10259,
    ENEMY_LANDING = 10260,

    ENEMY_SKILL = 10016,

    ENEMY_HIT_LIGHT = 10512,
    ENEMY_HIT_HEAVY = 10513,

    ENEMY_STUN = 10515,
    ENEMY_STAGGER = 10520,

    ENEMY_COMPETE = 11024,
    ENEMY_COMPETE_SUCCESS = 11025,

    ENEMY_SPAWN = 12048,
    ENEMY_DIE = 14096,
}

public enum ACTION_STATE_WEIGHT
{
    // Common
    COMMON_UPPER_EMPTY = 0,

    // Player
    PLAYER_IDLE = 0,
    PLAYER_WALK = 1,
    PLAYER_RUN = 2,

    PLAYER_EQUIP = 3,
    PLAYER_DRINK = 4,

    PLAYER_ATTACK_LIGHT_01 = 8,
    PLAYER_ATTACK_LIGHT_02 = 8,
    PLAYER_ATTACK_LIGHT_03 = 8,
    PLAYER_ATTACK_LIGHT_04 = 8,

    PLAYER_ATTACK_HEAVY_01 = 8,
    PLAYER_ATTACK_HEAVY_02 = 8,
    PLAYER_ATTACK_HEAVY_03 = 8,
    PLAYER_ATTACK_HEAVY_04 = 8,

    PLAYER_GUARD_IN = 8,
    PLAYER_GUARD_LOOP = 8,
    PLAYER_GUARD_OUT = 8,
    PLAYER_GUARD_BREAK = 9,

    PLAYER_PARRYING = 9,
    PLAYER_PARRYING_ATTACK = 10,

    PLAYER_SLIDE = 32,
    PLAYER_FALL = 33,
    PLAYER_LANDING = 34,

    PLAYER_SKILL_COUNTER = 64,
    PLAYER_ROLL = 65,

    PLAYER_RESONANCE_IN = 128,
    PLAYER_RESONANCE_LOOP = 129,
    PLAYER_RESONANCE_OUT = 130,

    PLAYER_HIT_LIGHT = 512,
    PLAYER_HIT_HEAVY = 513,
    PLAYER_HIT_HEAVY_LOOP = 514,
    PLAYER_STAND_UP = 515,
    PLAYER_STAND_ROLL = 516,

    PLAYER_STUN = 517,

    PLAYER_COMPETE = 1024,
    PLAYER_COMPETE_SUCCESS = 1025,
    PLAYER_SPAWN = 2048,
    PLAYER_DIE = 4096,

    // Enemy
    ENEMY_IDLE = 0,
    ENEMY_PATROL = 1,
    ENEMY_CHASE_WAIT = 2,
    ENEMY_CHASE_TURN = 3,
    ENEMY_CHASE_WALK = 4,
    ENEMY_CHASE_RUN = 5,

    ENEMY_SKILL = 8,

    ENEMY_SLIDE = 256,
    ENEMY_FALL = 257,
    ENEMY_LANDING = 258,

    ENEMY_HIT_LIGHT = 512,
    ENEMY_HIT_HEAVY = 513,

    ENEMY_STUN = 515,
    ENEMY_STAGGER = 520,

    ENEMY_COMPETE = 1024,
    ENEMY_COMPETE_SUCCESS = 1025,

    ENEMY_SPAWN = 2048,
    ENEMY_DIE = 4096,
}

public enum ACTOR_GROUND_STATE
{
    GROUNDING,
    FLOATING,
    SLIDING,
    FALLING
}
#endregion

#region Buff
public enum BUFF_TYPE
{
    NONE = 0,
}
public enum DEBUFF_TYPE
{
    NONE = 0,

    BURN = 10,
}
#endregion

#region Physics
#endregion

#region Layer
public enum PHYSICS_LAYER
{
    Terrain = 6,
    Player = 7,
    Enemy = 8,
    Die = 9
}

public enum ANIMATOR_LAYER
{
    BASE = 0,
    UPPER = 1,
}
#endregion

#region Enemy
public enum ENEMY_TYPE
{
    Normal,
    Elite,
    Boss
}
#endregion

#region UI
public enum UI_EVENT
{
    CLICK,
    PRESS
}
#endregion

#region Scene
public enum SCENE_TYPE
{
    Unknown,
    Title,
    Selection,
    Loading,
    Game,

    Test = 1000,
}

public enum SCENE_LIST
{
    // Scene Name = Build Index
    Title = 0,
    Selection = 1,
    Loading = 2,
    Fog_Canyon = 3,
    Forestia,
    Cave,

    Size,

    // Test
    Test = 1000,
}

public enum WEATHER_TYPE
{
    Sunny,
    Rain_Light,
    Rain_Heavy,
    Snow_Light,
    Snow_Heavy,
    Fog,
    Storm,

    Fireflies,
}
#endregion