public enum COMBAT_TYPE
{
    // Attack
    ATTACK_NORMAL = 0,
    ATTACK_LIGHT = 1,
    ATTACK_HEAVY = 2,
    ATTACK_STUN = 3,

    // Defense
    DEFENSE = 32,
    PARRYING = 64,
}

public enum BUFF_TYPE
{
    NONE = 0,
}
public enum DEBUFF_TYPE
{
    NONE = 0,

    BURN = 10,
}

public enum GREAT_SWORD_ATTACK_TYPE
{
    ATTACK_LIGHT_01,
    ATTACK_LIGHT_02,
    ATTACK_LIGHT_03,
    ATTACK_LIGHT_04,

    ATTACK_HEAVY_01,
    ATTACK_HEAVY_02,
    ATTACK_HEAVY_03_1,
    ATTACK_HEAVY_03_2,
    ATTACK_HEAVY_04_1,
    ATTACK_HEAVY_04_2,

    PARRYING_ATTACK,
    SKILL_COUNTER,
}

public enum LANCE_ATTACK_TYPE
{
    ATTACK_LIGHT_01,
    ATTACK_LIGHT_02,
    ATTACK_LIGHT_03,
    ATTACK_LIGHT_04,

    ATTACK_HEAVY_01,
    ATTACK_HEAVY_02,
    ATTACK_HEAVY_03,
    ATTACK_HEAVY_04_1,
    ATTACK_HEAVY_04_2,

    PARRYING_ATTACK,
    SKILL_COUNTER,
}