public enum ACTION_STATE
{
    // Common State
    COMMON_UPPER_EMPTY = 20000,
    COMMON_FALL = 20003,
    COMMON_DIE = 24096,

    // Player State
    // - Halberd
    PLAYER_HALBERD_IDLE = 0,
    PLAYER_HALBERD_WALK = 1,
    PLAYER_HALBERD_RUN = 2,

    PLAYER_HALBERD_EQUIP = 3,

    PLAYER_HALBERD_ATTACK_LIGHT_01 = 4,
    PLAYER_HALBERD_ATTACK_LIGHT_02 = 5,
    PLAYER_HALBERD_ATTACK_LIGHT_03 = 6,
    PLAYER_HALBERD_ATTACK_LIGHT_04 = 7,

    PLAYER_HALBERD_ATTACK_HEAVY_01 = 8,
    PLAYER_HALBERD_ATTACK_HEAVY_02 = 9,
    PLAYER_HALBERD_ATTACK_HEAVY_03 = 10,
    PLAYER_HALBERD_ATTACK_HEAVY_04 = 11,

    PLAYER_HALBERD_GUARD_IN = 12,
    PLAYER_HALBERD_GUARD_LOOP = 13,
    PLAYER_HALBERD_GUARD_OUT = 14,
    PLAYER_HALBERD_GUARD_BREAK = 15,
    PLAYER_HALBERD_PARRYING = 16,
    PLAYER_HALBERD_PARRYING_ATTACK = 17,

    PLAYER_HALBERD_SKILL_COUNTER = 18,

    // - Sword Shield
    PLAYER_SWORD_SHIELD_IDLE = 100,
    PLAYER_SWORD_SHIELD_WALK = 101,
    PLAYER_SWORD_SHIELD_RUN = 102,

    PLAYER_SWORD_SHIELD_EQUIP = 103,

    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_01 = 104,
    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_02 = 105,
    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_03 = 106,
    PLAYER_SWORD_SHIELD_ATTACK_LIGHT_04 = 107,
                                          
    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_01 = 108,
    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_02 = 109,
    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_03 = 110,
    PLAYER_SWORD_SHIELD_ATTACK_HEAVY_04 = 111,

    PLAYER_SWORD_SHIELD_GUARD_IN = 112,
    PLAYER_SWORD_SHIELD_GUARD_LOOP = 113,
    PLAYER_SWORD_SHIELD_GUARD_OUT = 114,
    PLAYER_SWORD_SHIELD_GUARD_BREAK = 115,
    PLAYER_SWORD_SHIELD_PARRYING = 116,
    PLAYER_SWORD_SHIELD_PARRYING_ATTACK = 117,

    // - Common
    PLAYER_ROLL = 256,
    PLAYER_LANDING = 258,

    PLAYER_HIT_LIGHT = 512,
    PLAYER_HIT_HEAVY = 513,
    PLAYER_HIT_HEAVY_LOOP = 514,
    PLAYER_STAND_UP = 515,
    PLAYER_STAND_ROLL = 516,

    PLAYER_STUN = 517,

    PLAYER_COMPETE = 1024,
    PLAYER_SPAWN = 2048,

    // Enemy State
    ENEMY_IDLE = 10000,
    ENEMY_PATROL = 10001,
    ENEMY_CHASE_WAIT = 10002,
    ENEMY_CHASE_WALK = 10003,
    ENEMY_CHASE_RUN = 10004,

    ENEMY_SKILL = 10016,

    ENEMY_HIT_LIGHT = 10512,
    ENEMY_HIT_HEAVY = 10513,

    ENEMY_STUN = 10515,
    ENEMY_STAGGER = 10520,

    ENEMY_COMPETE = 11024,
    ENEMY_COMPETE_DEFEAT = 11025,

    ENEMY_SPAWN = 12048,
}

public enum ACTION_STATE_WEIGHT
{
    // Common
    COMMON_UPPER_EMPTY = 0,

    // Player
    PLAYER_IDLE = 0,
    PLAYER_WALK = 1,
    PLAYER_RUN = 2,

    PLAYER_EQUIP = 3,

    PLAYER_ATTACK_LIGHT_01 = 8,
    PLAYER_ATTACK_LIGHT_02 = 8,
    PLAYER_ATTACK_LIGHT_03 = 8,
    PLAYER_ATTACK_LIGHT_04 = 8,

    PLAYER_ATTACK_HEAVY_01 = 8,
    PLAYER_ATTACK_HEAVY_02 = 8,
    PLAYER_ATTACK_HEAVY_03 = 8,
    PLAYER_ATTACK_HEAVY_04 = 8,

    PLAYER_GUARD_IN = 8,
    PLAYER_GUARD_LOOP = 8,
    PLAYER_GUARD_OUT = 8,
    PLAYER_GUARD_BREAK = 8,

    PLAYER_PARRYING = 8,
    PLAYER_PARRYING_ATTACK = 8,

    PLAYER_SKILL_COUNTER = 32,

    PLAYER_ROLL = 64,
    PLAYER_FALL = 65,
    PLAYER_LANDING = 66,

    PLAYER_HIT_LIGHT = 512,
    PLAYER_HIT_HEAVY = 513,
    PLAYER_HIT_HEAVY_LOOP = 514,
    PLAYER_STAND_UP = 515,
    PLAYER_STAND_ROLL = 516,

    PLAYER_STUN = 517,

    PLAYER_COMPETE = 1024,
    PLAYER_SPAWN = 2048,
    PLAYER_DIE = 4096,

    // Enemy
    ENEMY_IDLE = 0,
    ENEMY_PATROL = 1,
    ENEMY_CHASE_WAIT = 2,
    ENEMY_CHASE_WALK = 3,
    ENEMY_CHASE_RUN = 4,

    ENEMY_SKILL = 8,

    ENEMY_HIT_LIGHT = 512,
    ENEMY_HIT_HEAVY = 513,

    ENEMY_STUN = 515,
    ENEMY_STAGGER = 520,

    ENEMY_COMPETE = 1024,
    ENEMY_COMPETE_DEFEAT = 1025,

    ENEMY_SPAWN = 2048,
    ENEMY_DIE = 4096,
}

public enum INPUT_STATE
{
    Title,
    Selection,
    InGame,
    UI,
}