public enum COMBAT_TYPE
{
    // Attack
    ATTACK_NORMAL = 0,
    ATTACK_LIGHT = 1,
    ATTACK_HEAVY = 2,
    ATTACK_STUN = 3,

    // Guard
    GUARDABLE = 32,
    PARRYABLE = 64,
}

public enum BUFF_TYPE
{
    NONE = 0,
}
public enum DEBUFF_TYPE
{
    NONE = 0,

    BURN = 10,
}

public enum COMBAT_ACTION_TYPE
{
    // Halberd
    HALBERD_ATTACK_LIGHT_01,
    HALBERD_ATTACK_LIGHT_02,
    HALBERD_ATTACK_LIGHT_03,
    HALBERD_ATTACK_LIGHT_04,

    HALBERD_ATTACK_HEAVY_01,
    HALBERD_ATTACK_HEAVY_02,
    HALBERD_ATTACK_HEAVY_03_1,
    HALBERD_ATTACK_HEAVY_03_2,
    HALBERD_ATTACK_HEAVY_04_1,
    HALBERD_ATTACK_HEAVY_04_2,

    HALBERD_GUARD_IN,
    HALBERD_GUARD_LOOP,
    HALBERD_GUARD_OUT,
    HALBERD_GUARD_BREAK,
    HALBERD_PARRYING,
    HALBERD_PARRYING_ATTACK,

    HALBERD_SKILL_COUNTER,

    // Sword & Shield
    SWORD_SHIELD_ATTACK_LIGHT_01,
    SWORD_SHIELD_ATTACK_LIGHT_02,
    SWORD_SHIELD_ATTACK_LIGHT_03,
    SWORD_SHIELD_ATTACK_LIGHT_04,

    SWORD_SHIELD_ATTACK_HEAVY_01,
    SWORD_SHIELD_ATTACK_HEAVY_02,
    SWORD_SHIELD_ATTACK_HEAVY_03,
    SWORD_SHIELD_ATTACK_HEAVY_04_1,
    SWORD_SHIELD_ATTACK_HEAVY_04_2,
    SWORD_SHIELD_ATTACK_HEAVY_04_3,

    SWORD_SHIELD_GUARD_IN,
    SWORD_SHIELD_GUARD_LOOP,
    SWORD_SHIELD_GUARD_OUT,
    SWORD_SHIELD_GUARD_BREAK,
    SWORD_SHIELD_PARRYING,
    SWORD_SHIELD_PARRYING_ATTACK,
}